eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

server:
  port: 7008

spring:
  application:
    name: catalog-service
  graphql:
    path: /graphql
    graphiql:
      enabled: true
    playground:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/sol_catalog
    username: postgres
    password: 54321
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          validation:
            mode: none
    show-sql: true



