eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

server:
  port: 7003
grpc:
  server:
    port: 9090

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sol_payment
    username: postgres
    password: 54321
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          validation:
            mode: none
    show-sql: true



