eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
server:
  port: 7006
spring:
  application:
    name: notification-service
  data:
    mongodb:
      database: sol_notification
      port: 27017
      host: localhost
